/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/slideshow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Anonymous create. Returns id, share_url, write_token, edit_url.
         *
         *     The write_token is rendered exactly once, here. Losing it freezes
         *     the slideshow forever, which is why the SDK caches it locally
         *     immediately on the response.
         *
         *     The edit_url is also rendered exactly once at create time. Lost
         *     edit_urls can be recovered through GET /api/v1/slideshow/<slug>/
         *     edit-token/ as long as the caller still has the write_token. The
         *     SHA-256 hash of the supplied write_token is stamped onto the row
         *     here as the ownership credential the recovery endpoint compares
         *     against.
         */
        post: operations["slideshow_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slideshow/{slideshow_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Patch title, description, or summary. Auth: Bearer <write_token>. */
        patch: operations["slideshow_partial_update"];
        trace?: never;
    };
    "/api/slideshow/{slideshow_id}/slides/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Append a slide. Auth: Bearer <write_token>.
         *
         *     Position is server-assigned as max(existing) + 1. The unique
         *     constraint on (slideshow, position) is the safety net under
         *     concurrent appends; we read with ``select_for_update`` to keep
         *     the increment atomic in the common case.
         */
        post: operations["slideshow_slides_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slideshow/{slideshow_id}/slides/{position}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Replace image and/or caption. Auth: Bearer <write_token>. */
        patch: operations["slideshow_slides_partial_update"];
        trace?: never;
    };
    "/api/v1/gallery/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curated gallery feed for the home page.
         *
         *     Returns slideshows with `is_gallery=True`, ordered by
         *     `gallery_position` ascending then `-created_at`. Capped at a sane
         *     upper bound so a misconfigured admin entry can't blow up the
         *     payload.
         *
         *     Public, unauthenticated, rate-limited per the same throttling as
         *     the rest of the API.
         */
        get: operations["v1_gallery_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/edit-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Return the edit_token + edit_url for callers who can prove ownership.
         *
         *     Authentication: Bearer <write_token>. The supplied token's SHA-256
         *     must match `created_by_token_hash` on the row. 401 when the header
         *     is missing/empty; 403 when the token doesn't match; 404 when the
         *     slug is unknown.
         */
        get: operations["v1_slideshow_edit_token_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/rotate-edit-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Regenerate the edit_token. The old URL stops working immediately.
         *
         *     Authentication: same ownership check as the recovery endpoint. The
         *     new edit_token is generated server-side; the response shape mirrors
         *     the recovery endpoint so SDK callers can use the same parser.
         */
        post: operations["v1_slideshow_rotate_edit_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Response shape for the edit-token recovery + rotation endpoints.
         *
         *     Both endpoints return the same envelope: the bare ``edit_token``
         *     (so SDK callers can rebuild URLs against any base) plus the
         *     fully-resolved ``edit_url`` for direct display.
         */
        EditToken: {
            readonly edit_token: string;
            readonly edit_url: string;
        };
        /**
         * @description Public, read-only shape for the home-page gallery endpoint.
         *
         *     Strips every internal field — write_token, created_ip, gallery_position
         *     (an internal sort key), is_gallery (a curation flag) — and emits only
         *     the fields the gallery card needs to render. The cover image comes
         *     from the FIRST slide if any exist; absent otherwise.
         */
        GallerySlideshow: {
            /** Format: uuid */
            readonly id: string;
            /** @description Public, unguessable URL component used at /s/<share_token>. */
            readonly share_token: string;
            readonly title: string;
            readonly description: string;
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            readonly created_by: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            readonly created_by_url: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly cover_image_url: string | null;
            readonly slide_count: number;
            readonly share_url: string;
        };
        /**
         * @description * `image` - Image
         *     * `video` - Video
         * @enum {string}
         */
        MediaKindEnum: "image" | "video";
        /**
         * @description Create + update shape for slides. Media and caption only.
         *
         *     ``position`` is server-assigned on create and read-only on update;
         *     callers identify the slide by its URL position, not its database id.
         *     ``media_kind`` and ``media_content_type`` are server-set from the
         *     upload's content type via the views' validator.
         */
        PatchedSlideWriteRequest: {
            /** Format: binary */
            media?: string;
            caption?: string;
        };
        /** @description Patch shape. Title, description, summary, and creator credit all optional. */
        PatchedSlideshowPatchRequest: {
            title?: string;
            description?: string;
            summary?: string;
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
        };
        /**
         * @description Create + update shape for slides. Media and caption only.
         *
         *     ``position`` is server-assigned on create and read-only on update;
         *     callers identify the slide by its URL position, not its database id.
         *     ``media_kind`` and ``media_content_type`` are server-set from the
         *     upload's content type via the views' validator.
         */
        SlideWrite: {
            readonly id: number;
            readonly position: number;
            caption?: string;
            readonly media_url: string;
            /**
             * @description image | video; sniffed from upload Content-Type at the API boundary.
             *
             *     * `image` - Image
             *     * `video` - Video
             */
            readonly media_kind: components["schemas"]["MediaKindEnum"];
        };
        /**
         * @description Create + update shape for slides. Media and caption only.
         *
         *     ``position`` is server-assigned on create and read-only on update;
         *     callers identify the slide by its URL position, not its database id.
         *     ``media_kind`` and ``media_content_type`` are server-set from the
         *     upload's content type via the views' validator.
         */
        SlideWriteRequest: {
            /** Format: binary */
            media?: string;
            caption?: string;
        };
        /**
         * @description Create-time shape. Renders ``write_token`` and ``edit_url`` exactly once.
         *
         *     Both fields are credentials (or near-credentials):
         *     - ``write_token`` is the bearer credential the SDK keeps locally
         *     - ``edit_url`` embeds the per-slideshow ``edit_token`` in its query
         *       string, granting public-side edit access to anyone who holds it
         *
         *     Neither field appears in any other serializer. Recovery for
         *     ``edit_url`` happens via GET /api/v1/slideshow/<slug>/edit-token/
         *     (authenticated by the write_token); ``write_token`` itself is
         *     never recoverable.
         */
        SlideshowCreate: {
            /** Format: uuid */
            readonly id: string;
            title?: string;
            description?: string;
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
            readonly share_url: string;
            readonly edit_url: string;
            readonly write_token: string;
        };
        /**
         * @description Create-time shape. Renders ``write_token`` and ``edit_url`` exactly once.
         *
         *     Both fields are credentials (or near-credentials):
         *     - ``write_token`` is the bearer credential the SDK keeps locally
         *     - ``edit_url`` embeds the per-slideshow ``edit_token`` in its query
         *       string, granting public-side edit access to anyone who holds it
         *
         *     Neither field appears in any other serializer. Recovery for
         *     ``edit_url`` happens via GET /api/v1/slideshow/<slug>/edit-token/
         *     (authenticated by the write_token); ``write_token`` itself is
         *     never recoverable.
         */
        SlideshowCreateRequest: {
            title?: string;
            description?: string;
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
        };
        /** @description Patch shape. Title, description, summary, and creator credit all optional. */
        SlideshowPatch: {
            /** Format: uuid */
            readonly id: string;
            title?: string;
            description?: string;
            summary?: string;
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    slideshow_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SlideshowCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowCreate"];
                };
            };
        };
    };
    slideshow_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slideshow_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSlideshowPatchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowPatch"];
                };
            };
        };
    };
    slideshow_slides_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slideshow_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["SlideWriteRequest"];
                "application/json": components["schemas"]["SlideWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideWrite"];
                };
            };
        };
    };
    slideshow_slides_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position: number;
                slideshow_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedSlideWriteRequest"];
                "application/json": components["schemas"]["PatchedSlideWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideWrite"];
                };
            };
        };
    };
    v1_gallery_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GallerySlideshow"][];
                };
            };
        };
    };
    v1_slideshow_edit_token_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditToken"];
                };
            };
        };
    };
    v1_slideshow_rotate_edit_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditToken"];
                };
            };
        };
    };
}
