/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/slideshow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Anonymous create. Returns id, share_url, write_token, edit_url.
         *
         *     The write_token is rendered exactly once, here. Losing it freezes
         *     the slideshow forever, which is why the SDK caches it locally
         *     immediately on the response.
         *
         *     The edit_url is also rendered exactly once at create time. Lost
         *     edit_urls can be recovered through GET /api/v1/slideshow/<slug>/
         *     edit-token/ as long as the caller still has the write_token. The
         *     SHA-256 hash of the supplied write_token is stamped onto the row
         *     here as the ownership credential the recovery endpoint compares
         *     against.
         */
        post: operations["slideshow_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slideshow/{slideshow_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description PATCH title/description/summary or DELETE the whole slideshow.
         *
         *     Auth: Bearer <write_token>. DELETE cascades to all slides via the
         *     Slide.slideshow FK; the underlying R2 objects are NOT cleaned up
         *     here (django-storages doesn't delete files on model.delete by
         *     default), so empty bucket cruft accumulates. Acceptable for v0.1
         *     with low traffic; revisit when storage costs matter.
         */
        delete: operations["slideshow_destroy"];
        options?: never;
        head?: never;
        /**
         * @description PATCH title/description/summary or DELETE the whole slideshow.
         *
         *     Auth: Bearer <write_token>. DELETE cascades to all slides via the
         *     Slide.slideshow FK; the underlying R2 objects are NOT cleaned up
         *     here (django-storages doesn't delete files on model.delete by
         *     default), so empty bucket cruft accumulates. Acceptable for v0.1
         *     with low traffic; revisit when storage costs matter.
         */
        patch: operations["slideshow_partial_update"];
        trace?: never;
    };
    "/api/slideshow/{slideshow_id}/slides/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Append a slide. Auth: Bearer <write_token>.
         *
         *     Position is server-assigned as max(existing) + 1. The unique
         *     constraint on (slideshow, position) is the safety net under
         *     concurrent appends; we read with ``select_for_update`` to keep
         *     the increment atomic in the common case.
         */
        post: operations["slideshow_slides_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slideshow/{slideshow_id}/slides/{position}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Replace image and/or caption. Auth: Bearer <write_token>. */
        patch: operations["slideshow_slides_partial_update"];
        trace?: never;
    };
    "/api/v1/gallery/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Curated gallery feed for the home page.
         *
         *     Returns slideshows with `is_gallery=True`, ordered by
         *     `gallery_position` ascending then `-created_at`. Capped at 12 so a
         *     misconfigured admin entry can't blow up the payload.
         *
         *     Curation flips the `is_gallery` flag and sets `gallery_position`.
         *     Two ways to flip it:
         *     - Django admin (privileged user account)
         *     - The `agentclip slideshow feature <token>` CLI, which hits the
         *       admin endpoint at `/api/v1/slideshow/<share_token>/feature/`
         *       authenticated by `AGENTCLIP_ADMIN_TOKEN`. The CLI path lets a
         *       curator (or an agent given the admin token) reorder the gallery
         *       without a Django admin trip — and without a redeploy.
         *
         *     Public, unauthenticated, rate-limit-free (read-only).
         */
        get: operations["v1_gallery_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Public read of one slideshow by share_token.
         *
         *     Replaces the deleted Django template view. Anonymous, unauthenticated,
         *     rate-limit-free (read-only — abuse vectors are the same as a CDN
         *     fetch). The Next.js viewer page (`/s/[token]`) calls this endpoint
         *     via the typed client; agents and integrations are welcome to too.
         *
         *     Returns 200 with `SlideshowPublicSerializer` on hit, 404 on miss.
         *     Slides are prefetched in position order so the response renders in
         *     one query.
         */
        get: operations["v1_slideshow_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/clip.mp4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Serve the rendered MP4 for a slideshow, lazy-render on miss.
         *
         *     Public, unauthenticated — the share_token IS the access credential.
         *     Consumers: GitHub PR inline-video fetcher, Slack/Discord unfurl,
         *     Twitter Player Card resolver, anyone who pastes the link.
         */
        get: operations["v1_slideshow_clip.mp4_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/clip.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Serve the rendered PDF walkthrough, lazy-render on miss. */
        get: operations["v1_slideshow_clip.pdf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/edit-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Return the edit_token + edit_url for callers who can prove ownership.
         *
         *     Authentication: Bearer <write_token>. The supplied token's SHA-256
         *     must match `created_by_token_hash` on the row. 401 when the header
         *     is missing/empty; 403 when the token doesn't match; 404 when the
         *     slug is unknown.
         */
        get: operations["v1_slideshow_edit_token_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/feature/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Flip is_gallery on a slideshow. Auth: Bearer AGENTCLIP_ADMIN_TOKEN.
         *
         *     POST   {position?: int} → set is_gallery=True, gallery_position=<position>
         *     DELETE                  → set is_gallery=False (drops from gallery)
         *
         *     The slideshow row is the source of truth for curation. Calling
         *     POST repeatedly with different positions is the supported way to
         *     reorder. POST is idempotent in the is_gallery sense — calling it
         *     twice on a featured slideshow is fine; the second call updates
         *     the position.
         */
        post: operations["v1_slideshow_feature_create"];
        /**
         * @description Flip is_gallery on a slideshow. Auth: Bearer AGENTCLIP_ADMIN_TOKEN.
         *
         *     POST   {position?: int} → set is_gallery=True, gallery_position=<position>
         *     DELETE                  → set is_gallery=False (drops from gallery)
         *
         *     The slideshow row is the source of truth for curation. Calling
         *     POST repeatedly with different positions is the supported way to
         *     reorder. POST is idempotent in the is_gallery sense — calling it
         *     twice on a featured slideshow is fine; the second call updates
         *     the position.
         */
        delete: operations["v1_slideshow_feature_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/narrate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Generate per-slide narration MP3s. Auth: Bearer <write_token>.
         *
         *     Loops the slideshow's slides and synthesizes audio from each
         *     caption via OpenAI TTS-1-HD. Idempotent by default — slides that
         *     already have audio are skipped. Pass `force=true` to regenerate
         *     everything, or `dry_run=true` to estimate cost without spending.
         *
         *     Auth model: same as slide_add — only the write_token holder can
         *     narrate. The token is presented in the Authorization header
         *     exactly like an SDK upload request.
         *
         *     Response: the public slideshow shape with `audio_url` populated
         *     on each newly-narrated slide. The response also includes a
         *     `narration` block with per-slide outcomes and total cost so the
         *     caller can render a summary or surface the spend.
         *
         *     Cost: ~$0.030 per 1K caption characters. A 4-slide walkthrough
         *     with ~150-char captions is ~$0.018 per run.
         */
        post: operations["v1_slideshow_narrate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/rotate-edit-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Regenerate the edit_token. The old URL stops working immediately.
         *
         *     Authentication: same ownership check as the recovery endpoint. The
         *     new edit_token is generated server-side; the response shape mirrors
         *     the recovery endpoint so SDK callers can use the same parser.
         */
        post: operations["v1_slideshow_rotate_edit_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/slides/{position}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Delete a slide via the edit_token. Auth: Bearer <edit_token>.
         *
         *     Positions of remaining slides are NOT renumbered — the gap is
         *     preserved so existing public links to higher-numbered positions
         *     stay valid as long as those slides exist. Renumbering on delete
         *     would silently rewrite shareable URLs.
         */
        delete: operations["v1_slideshow_slides_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slideshow/{share_token}/slides/{position}/caption/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Edit a slide's caption via the edit_token. Auth: Bearer <edit_token>. */
        patch: operations["v1_slideshow_slides_caption_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Response shape for the edit-token recovery + rotation endpoints.
         *
         *     Both endpoints return the same envelope: the bare ``edit_token``
         *     (so SDK callers can rebuild URLs against any base) plus the
         *     fully-resolved ``edit_url`` for direct display.
         */
        EditToken: {
            readonly edit_token: string;
            readonly edit_url: string;
        };
        /**
         * @description Public, read-only shape for the home-page gallery endpoint.
         *
         *     Strips every internal field — write_token, created_ip, gallery_position
         *     (an internal sort key), is_gallery (a curation flag) — and emits only
         *     the fields the gallery card needs to render. The cover image comes
         *     from the FIRST slide if any exist; absent otherwise.
         */
        GallerySlideshow: {
            /** Format: uuid */
            readonly id: string;
            /** @description Public, unguessable URL component used at /s/<share_token>. */
            readonly share_token: string;
            readonly title: string;
            readonly description: string;
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            readonly created_by: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            readonly created_by_url: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly cover_image_url: string | null;
            readonly slide_count: number;
            readonly share_url: string;
            /** @description Show as the home-page hero polaroid. Curated via the admin. When multiple slideshows have is_hero=True the API picks the most recently featured. Independent of is_gallery. */
            readonly is_hero: boolean;
        };
        /**
         * @description * `image` - Image
         *     * `video` - Video
         * @enum {string}
         */
        MediaKindEnum: "image" | "video";
        /**
         * @description Edit-page caption update body.
         *
         *     The edit-token-authenticated endpoint accepts only `caption` —
         *     callers wanting to change media must use the write_token-protected
         *     `/api/slideshow/<id>/slides/<position>/` route. Keeping the surface
         *     narrow makes the security boundary easier to reason about.
         */
        PatchedSlideCaptionEditRequest: {
            caption?: string;
        };
        /**
         * @description Create + update shape for slides. Media and caption only.
         *
         *     ``position`` is server-assigned on create and read-only on update;
         *     callers identify the slide by its URL position, not its database id.
         *     ``media_kind`` and ``media_content_type`` are server-set from the
         *     upload's content type via the views' validator.
         *
         *     ``caption`` is required on create. Silent slides with no spoken
         *     context are not a valid output state — the agent should always
         *     write a caption, even one sentence ("Step 4: same result"). The
         *     PATCH path remains tolerant via partial=True (a caller updating
         *     just the media doesn't have to repeat the caption).
         */
        PatchedSlideWriteRequest: {
            /** @description Short eyebrow title for the slide. Renders above the image in the viewer; gives the slideshow visual hierarchy and makes long runs skimmable. The bundled agentclip skill tells agents to write a 3-7 word title plus a longer caption per slide. */
            title?: string;
            /** Format: binary */
            media?: string;
            caption?: string;
        };
        /** @description Patch shape. Title, description, summary, run_type, and creator credit all optional. */
        PatchedSlideshowPatchRequest: {
            title?: string;
            description?: string;
            summary?: string;
            /**
             * @description What kind of QA run this clip represents. Drives the narration voice + pacing for the whole clip; the agent skill picks one heuristically from the trigger phrase.
             *
             *     * `bug_repro` - Bug repro
             *     * `smoke_test` - Smoke test
             *     * `demo` - Demo
             *     * `onboarding_eval` - Onboarding eval
             *     * `competitive_teardown` - Competitive teardown
             *     * `generic` - Generic
             */
            run_type?: components["schemas"]["RunTypeEnum"];
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
        };
        /**
         * @description * `bug_repro` - Bug repro
         *     * `smoke_test` - Smoke test
         *     * `demo` - Demo
         *     * `onboarding_eval` - Onboarding eval
         *     * `competitive_teardown` - Competitive teardown
         *     * `generic` - Generic
         * @enum {string}
         */
        RunTypeEnum: "bug_repro" | "smoke_test" | "demo" | "onboarding_eval" | "competitive_teardown" | "generic";
        SlidePublic: {
            readonly id: number;
            readonly position: number;
            /** @description Short eyebrow title for the slide. Renders above the image in the viewer; gives the slideshow visual hierarchy and makes long runs skimmable. The bundled agentclip skill tells agents to write a 3-7 word title plus a longer caption per slide. */
            readonly title: string;
            readonly caption: string;
            readonly media_url: string;
            /**
             * @description image | video; sniffed from upload Content-Type at the API boundary.
             *
             *     * `image` - Image
             *     * `video` - Video
             */
            readonly media_kind: components["schemas"]["MediaKindEnum"];
            readonly audio_url: string | null;
            /** @description OpenAI TTS voice used to generate `audio` (e.g. "nova"). Blank when audio is unset. */
            readonly audio_voice: string;
            /** @description Duration of `audio` in milliseconds. 0 when audio is unset or duration extraction failed; the player falls back to indeterminate progress until the metadata loads. */
            readonly audio_duration_ms: number;
        };
        /**
         * @description Create + update shape for slides. Media and caption only.
         *
         *     ``position`` is server-assigned on create and read-only on update;
         *     callers identify the slide by its URL position, not its database id.
         *     ``media_kind`` and ``media_content_type`` are server-set from the
         *     upload's content type via the views' validator.
         *
         *     ``caption`` is required on create. Silent slides with no spoken
         *     context are not a valid output state — the agent should always
         *     write a caption, even one sentence ("Step 4: same result"). The
         *     PATCH path remains tolerant via partial=True (a caller updating
         *     just the media doesn't have to repeat the caption).
         */
        SlideWrite: {
            readonly id: number;
            readonly position: number;
            /** @description Short eyebrow title for the slide. Renders above the image in the viewer; gives the slideshow visual hierarchy and makes long runs skimmable. The bundled agentclip skill tells agents to write a 3-7 word title plus a longer caption per slide. */
            title?: string;
            caption: string;
            readonly media_url: string;
            /**
             * @description image | video; sniffed from upload Content-Type at the API boundary.
             *
             *     * `image` - Image
             *     * `video` - Video
             */
            readonly media_kind: components["schemas"]["MediaKindEnum"];
        };
        /**
         * @description Create + update shape for slides. Media and caption only.
         *
         *     ``position`` is server-assigned on create and read-only on update;
         *     callers identify the slide by its URL position, not its database id.
         *     ``media_kind`` and ``media_content_type`` are server-set from the
         *     upload's content type via the views' validator.
         *
         *     ``caption`` is required on create. Silent slides with no spoken
         *     context are not a valid output state — the agent should always
         *     write a caption, even one sentence ("Step 4: same result"). The
         *     PATCH path remains tolerant via partial=True (a caller updating
         *     just the media doesn't have to repeat the caption).
         */
        SlideWriteRequest: {
            /** @description Short eyebrow title for the slide. Renders above the image in the viewer; gives the slideshow visual hierarchy and makes long runs skimmable. The bundled agentclip skill tells agents to write a 3-7 word title plus a longer caption per slide. */
            title?: string;
            /** Format: binary */
            media?: string;
            caption: string;
        };
        /**
         * @description Create-time shape. Renders ``write_token`` and ``edit_url`` exactly once.
         *
         *     Both fields are credentials (or near-credentials):
         *     - ``write_token`` is the bearer credential the SDK keeps locally
         *     - ``edit_url`` embeds the per-slideshow ``edit_token`` in its query
         *       string, granting public-side edit access to anyone who holds it
         *
         *     Neither field appears in any other serializer. Recovery for
         *     ``edit_url`` happens via GET /api/v1/slideshow/<slug>/edit-token/
         *     (authenticated by the write_token); ``write_token`` itself is
         *     never recoverable.
         */
        SlideshowCreate: {
            /** Format: uuid */
            readonly id: string;
            title?: string;
            description?: string;
            /**
             * @description What kind of QA run this clip represents. Drives the narration voice + pacing for the whole clip; the agent skill picks one heuristically from the trigger phrase.
             *
             *     * `bug_repro` - Bug repro
             *     * `smoke_test` - Smoke test
             *     * `demo` - Demo
             *     * `onboarding_eval` - Onboarding eval
             *     * `competitive_teardown` - Competitive teardown
             *     * `generic` - Generic
             */
            run_type?: components["schemas"]["RunTypeEnum"];
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
            readonly share_url: string;
            readonly edit_url: string;
            readonly clip_mp4_url: string;
            readonly clip_pdf_url: string;
            readonly embed_url: string;
            readonly write_token: string;
        };
        /**
         * @description Create-time shape. Renders ``write_token`` and ``edit_url`` exactly once.
         *
         *     Both fields are credentials (or near-credentials):
         *     - ``write_token`` is the bearer credential the SDK keeps locally
         *     - ``edit_url`` embeds the per-slideshow ``edit_token`` in its query
         *       string, granting public-side edit access to anyone who holds it
         *
         *     Neither field appears in any other serializer. Recovery for
         *     ``edit_url`` happens via GET /api/v1/slideshow/<slug>/edit-token/
         *     (authenticated by the write_token); ``write_token`` itself is
         *     never recoverable.
         */
        SlideshowCreateRequest: {
            title?: string;
            description?: string;
            /**
             * @description What kind of QA run this clip represents. Drives the narration voice + pacing for the whole clip; the agent skill picks one heuristically from the trigger phrase.
             *
             *     * `bug_repro` - Bug repro
             *     * `smoke_test` - Smoke test
             *     * `demo` - Demo
             *     * `onboarding_eval` - Onboarding eval
             *     * `competitive_teardown` - Competitive teardown
             *     * `generic` - Generic
             */
            run_type?: components["schemas"]["RunTypeEnum"];
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
        };
        /** @description Patch shape. Title, description, summary, run_type, and creator credit all optional. */
        SlideshowPatch: {
            /** Format: uuid */
            readonly id: string;
            title?: string;
            description?: string;
            summary?: string;
            /**
             * @description What kind of QA run this clip represents. Drives the narration voice + pacing for the whole clip; the agent skill picks one heuristically from the trigger phrase.
             *
             *     * `bug_repro` - Bug repro
             *     * `smoke_test` - Smoke test
             *     * `demo` - Demo
             *     * `onboarding_eval` - Onboarding eval
             *     * `competitive_teardown` - Competitive teardown
             *     * `generic` - Generic
             */
            run_type?: components["schemas"]["RunTypeEnum"];
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            created_by?: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            created_by_url?: string;
        };
        /** @description Read-only shape for /s/<share_token> and the public API. */
        SlideshowPublic: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly description: string;
            readonly summary: string;
            /** @description Display credit for the run, e.g. "Eric Elizes". Optional. */
            readonly created_by: string;
            /**
             * Format: uri
             * @description Optional URL the creator credit links to (portfolio, GitHub, etc.).
             */
            readonly created_by_url: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly share_url: string;
            readonly clip_mp4_url: string;
            readonly clip_pdf_url: string;
            readonly embed_url: string;
            readonly poster_image_url: string | null;
            readonly slides: components["schemas"]["SlidePublic"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    slideshow_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SlideshowCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowCreate"];
                };
            };
        };
    };
    slideshow_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slideshow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowPatch"];
                };
            };
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    slideshow_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slideshow_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSlideshowPatchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowPatch"];
                };
            };
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    slideshow_slides_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slideshow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SlideWriteRequest"];
                "application/json": components["schemas"]["SlideWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideWrite"];
                };
            };
        };
    };
    slideshow_slides_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position: number;
                slideshow_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedSlideWriteRequest"];
                "application/json": components["schemas"]["PatchedSlideWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideWrite"];
                };
            };
        };
    };
    v1_gallery_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GallerySlideshow"][];
                };
            };
        };
    };
    v1_slideshow_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowPublic"];
                };
            };
        };
    };
    "v1_slideshow_clip.mp4_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "v1_slideshow_clip.pdf_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_slideshow_edit_token_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditToken"];
                };
            };
        };
    };
    v1_slideshow_feature_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                type: {
                    [key: string]: unknown;
                };
                properties: unknown;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowPublic"];
                };
            };
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_slideshow_feature_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowPublic"];
                };
            };
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_slideshow_narrate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                type: {
                    [key: string]: unknown;
                };
                properties: unknown;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideshowPublic"];
                };
            };
        };
    };
    v1_slideshow_rotate_edit_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditToken"];
                };
            };
        };
    };
    v1_slideshow_slides_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position: number;
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_slideshow_slides_caption_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position: number;
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSlideCaptionEditRequest"];
                "multipart/form-data": components["schemas"]["PatchedSlideCaptionEditRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSlideCaptionEditRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideWrite"];
                };
            };
        };
    };
}
