# Generated by Django 6.0.5 on 2026-05-05 17:57

import django.db.models.deletion
import slideshows.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(default=slideshows.models._share_token, editable=False, help_text='Public, unguessable URL component used at /s/<share_token>.', max_length=32, unique=True)),
                ('write_token', models.CharField(default=slideshows.models._write_token, editable=False, help_text='Bearer credential. Whoever holds it can mutate this slideshow.', max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['share_token'], name='slideshows__share_t_c74573_idx')],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=slideshows.models._slide_image_path)),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='slideshows.slideshow')),
            ],
            options={
                'ordering': ('slideshow', 'position'),
                'constraints': [models.UniqueConstraint(fields=('slideshow', 'position'), name='unique_slide_position_per_slideshow')],
            },
        ),
    ]
