# Generated by Django 6.0.5 on 2026-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0003_edit_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='media_bytes',
            field=models.PositiveIntegerField(default=0, help_text='Size of the uploaded media in bytes. Populated at slide-add time; used to enforce MAX_BYTES_PER_SLIDESHOW without re-reading the storage backend on every request.'),
        ),
    ]
