# Generated by Django 6.0.5 on 2026-05-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0005_slide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='featured_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent feature event. Null if never featured.', null=True),
        ),
    ]
