# Generated by Django 6.0.5 on 2026-05-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0006_slideshow_featured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='is_hero',
            field=models.BooleanField(db_index=True, default=False, help_text='Show as the home-page hero polaroid. Curated via the admin. When multiple slideshows have is_hero=True the API picks the most recently featured. Independent of is_gallery.'),
        ),
    ]
