# Generated by Django 6.0.5 on 2026-05-07 14:40

import slideshows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0007_slideshow_is_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='audio',
            field=models.FileField(blank=True, help_text='Optional narration MP3 generated from `caption`. Populated by the `narrate` management command; absent until then.', null=True, upload_to=slideshows.models._slide_audio_path),
        ),
        migrations.AddField(
            model_name='slide',
            name='audio_duration_ms',
            field=models.PositiveIntegerField(default=0, help_text='Duration of `audio` in milliseconds. 0 when audio is unset or duration extraction failed; the player falls back to indeterminate progress until the metadata loads.'),
        ),
        migrations.AddField(
            model_name='slide',
            name='audio_voice',
            field=models.CharField(blank=True, default='', help_text='OpenAI TTS voice used to generate `audio` (e.g. "nova"). Blank when audio is unset.', max_length=32),
        ),
    ]
