# Generated by Django 6.0.5 on 2026-05-07 18:32

import slideshows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0008_slide_audio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='poster_image',
            field=models.FileField(blank=True, help_text='OG/Twitter poster image (1200x630 JPEG) extracted from the first slide at MP4-render time. Drives link-unfurl previews in Slack, iMessage, Twitter, Linear, etc.', null=True, upload_to=slideshows.models._render_path),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='render_version',
            field=models.PositiveIntegerField(default=0, help_text='Monotonic counter bumped whenever a slideshow mutation invalidates rendered MP4/PDF/poster artifacts. The render storage path includes this value so a bump yields a fresh path with no cache headaches.'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='rendered_mp4',
            field=models.FileField(blank=True, help_text='Server-rendered MP4 of the slideshow (per-slide image + narration MP3 stitched via ffmpeg). Populated lazily on first external fetch and pre-warmed on set_summary; cleared by bump_render_version.', null=True, upload_to=slideshows.models._render_path),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='rendered_pdf',
            field=models.FileField(blank=True, help_text='Server-rendered branded PDF walkthrough. Same lifecycle as rendered_mp4.', null=True, upload_to=slideshows.models._render_path),
        ),
    ]
