# Generated by Django 6.0.5 on 2026-05-07 21:28

import slideshows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0009_slideshow_render_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='intro_audio',
            field=models.FileField(blank=True, help_text='Spoken intro MP3 generated from `description`. Played over the title card frame at the start of the rendered MP4. Voice matches the rest of the clip per `run_type`.', null=True, upload_to=slideshows.models._render_path),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='outro_audio',
            field=models.FileField(blank=True, help_text='Spoken outro MP3 generated from `summary`. Played over the end card frame at the end of the rendered MP4.', null=True, upload_to=slideshows.models._render_path),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='run_type',
            field=models.CharField(choices=[('bug_repro', 'Bug repro'), ('smoke_test', 'Smoke test'), ('demo', 'Demo'), ('onboarding_eval', 'Onboarding eval'), ('competitive_teardown', 'Competitive teardown'), ('generic', 'Generic')], default='generic', help_text='What kind of QA run this clip represents. Drives the narration voice + pacing for the whole clip; the agent skill picks one heuristically from the trigger phrase.', max_length=24),
        ),
    ]
