import type { StorybookConfig } from '@storybook/nextjs'

const config: StorybookConfig = {
  framework: {
    name: '@storybook/nextjs',
    options: {},
  },
  // Stories live alongside components, one folder per primitive/composite/pattern.
  stories: ['../components/**/*.stories.@(ts|tsx)', '../app/**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-a11y',     // axe-core checks per story
    '@storybook/addon-docs',     // autogenerated docs from JSDoc + props
    '@storybook/addon-themes',   // light/dark toggle in the toolbar
  ],
  staticDirs: ['../public'],
  typescript: {
    check: false,           // tsc runs separately via pnpm type:check
    reactDocgen: 'react-docgen-typescript',
  },
}

export default config
