# fly.toml app configuration file generated for agentclip-web on 2026-05-06T18:43:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agentclip-web'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  AGENTCLIP_API_URL = 'http://agentclip-api.internal:8000'
  NEXT_PUBLIC_AGENTCLIP_API_URL = 'https://api.agentclip.dev'
  NEXT_TELEMETRY_DISABLED = '1'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 160

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
